### ISSUE TITLE
Still empty lines added (like fixed #7)

### ISSUE THREAD

**Issue by SnowMB** [chdemko/pandoc-latex-environment#24]
Tested with version 1.1.6.5 from pip.

config: 
```yaml
pandoc-latex-environment:
  noteblock: [note]
  tipblock: [tip]
  warningblock: [warning]
  cautionblock: [caution]
  importantblock: [important]
```

```md
::: note
Testline
:::
```

results in

```latex
\begin{noteblock}

Testline

\end{noteblock}
```

Expected: 

```latex
\begin{noteblock}
Testline
\end{noteblock}
```
